name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.POST_COMMIT_UPDATES_DEPLOY_KEY }}
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: npm
      - name: Format alerts
        run: |
          make fmt
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git status
          cat <<EOF | git commit -F - || true
          Auto formatted alerts by GitHub
          EOF
          git push
      - name: Run tests
        run: make test
      - name: Lint
        run: make lint
